{
 "title": "nwaku single node dashboard",
 "description": "Basic metrics for a single running nwaku node",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Start Times (UTC)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"nwaku\"}*1000"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "waku_version{instance=\"nwaku.nwaku.public.dappnode:9090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers{job=\"nwaku\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "libp2p_pubsub_peers{instance=\"nwaku.nwaku.public.dappnode:9090\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Rx/Tx Traffic (MBps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{instance=\"nwaku.nwaku.public.dappnode:9090\", direction=\"in\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    },
    {
     "expr": "rate(libp2p_network_bytes_total{instance=\"nwaku.nwaku.public.dappnode:9090\",direction=\"out\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "LibP2P Dials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "libp2p_total_dial_attempts_total{}",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "libp2p_failed_dials_total{}", "legendFormat": "{{__name__}}" },
    {
     "expr": "libp2p_successful_dials_total{}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Messages (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(increase(waku_node_messages_total[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Heap allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Nim Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(nim_gc_mem_bytes{}[$__interval])"
    }
   ]
  },
  {
   "title": "Waku Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (type)(increase(waku_peers_errors{job=\"nwaku\"}[$__rate_interval]))",
     "legendFormat": "peer {{type}}"
    },
    {
     "expr": "sum by (type)(increase(waku_store_errors{job=\"nwaku\"}[$__rate_interval]))",
     "legendFormat": "store {{type}}"
    },
    {
     "expr": "sum by (type)(increase(waku_node_errors{job=\"nwaku\"}[$__rate_interval]))",
     "legendFormat": "node {{type}}"
    }
   ]
  },
  {
   "title": "Total Content Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "count(count by (contentTopic)(waku_node_messages_total))",
     "legendFormat": "content topics"
    }
   ]
  },
  {
   "title": "Waku Node Filters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "waku_node_filters{job=\"nwaku\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waku Node Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "waku_node_errors{job=\"nwaku\"}",
     "legendFormat": "{{type}}: {{instance}}"
    }
   ]
  }
 ]
}